# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '16'
      jdkArchitectureOption: x64
      jdkSourceOption: 'AzureStorage'
      azureResourceManagerEndpoint: Azure Resource Manager
      azureStorageAccountName: your_azure_blob_storage_name
      azureContainerName: jdks
      azureCommonVirtualFile: 'openjdk.zip'
      jdkDestinationDirectory: '$(agent.toolsDirectory)/jdk16'
      cleanDestinationDirectory: true