name: Code Scan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  CodeScan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Detekt
      - run: ./gradlew detekt