name: Code Scan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  CodeScan:
    runs-on: ubuntu-latest

    steps:
      - name: Setup actions
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Detekt
      - run: ./gradlew detekt