name: Android Testing
on:
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "fix/*"
      - "config/*"
      - "main"
  pull_request:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "fix/*"
      - "config/*"
      - "main"
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}